version: "3"

services:
  redis:
    container_name: redis
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379

  db:
    container_name: db
    restart: always
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    env_file:
    - .env
    volumes: 
      - db:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: config/backend.dockerfile
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/backend
    environment:
      - UWSGI_PY_AUTORELOAD=1 # development only
    env_file:
      - .env
    ports:
      - 8000:8000

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: config/backend.dockerfile
    command: "celery -A core worker -l INFO"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - redis
    env_file:
      - .env

  flower:
    container_name: flower
    image: mher/flower
    env_file:
      - .env
    ports:
      - 8888:8888

  celery-beat:
    container_name: celery-beat
    build:
      context: .
      dockerfile: config/backend.dockerfile
    command: "celery -A core beat -l INFO"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - redis
    env_file:
      - .env

  api_docs:
    container_name: api_docs
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./backend/schema.yml:/schema.yml
    

volumes:
  db:
    driver: local
